### ISSUE TITLE
Overlapping requests do not respect longest required time

### ISSUE THREAD

**Issue by matthewcbaker** [aws-samples/iam-identity-center-team#104]
**Describe the bug**
If you have two requests for the same access level (Account + Role) then the one that finishes first will remove your access, even though you may still have a valid reason for having it.

**To Reproduce**
1. Request access for Account A with Role X, for ticket T1
2. Request access for Account A with Role X, for ticket T2
3. Approve both requests (if set to require approval)
4. Look in 'Active access'.  You have two 'in progress', one for T1, the other for T2.
5. Revoke your access for your work on ticket T1
6. Look in 'Active access'.  You have one 'in progress', for T2.
7. You no longer have access to the Role, even though you are scheduled to be working on T2.

**Expected behavior**
Once all active access finishes (for both T1 and T2) then revoke the access.

**Additional context**
* Release installed was 1.1.0
* This has not been tested by waiting for 1h to see what would happen if T1 had 'ended' rather than been 'revoked'.  The workflow diagrams indicate that the behaviour would have been the same though.

**Comment by danbdo** [comment]
For this case I would argue: TEAM should be just be a tool to govern access, and make the ticket number just an informational aspect for the approvers.
So for your second event aboveI would expect TEAM to reject/ignore the request altogether.
Otherwise what should TEAM do if an approver accepts the first, but rejects the second request?

**Comment by matthewcbaker** [comment]
Thank you for your comment @danbdo, and having thought about it, I have a few things to consider:

> the ticket number [is] just an informational aspect for the approvers

I agree.  It is also historical information for the requesters, the business and for the auditors.

> So for your second event above I would expect TEAM to reject/ignore the request altogether.
> Otherwise what should TEAM do if an approver accepts the first, but rejects the second request?

I believe:
* It is possible to know if they will _theoretically_ overlap at submission time, if the theory is based on immediate (or not required) approval
  * In this scenario it would be possible to notify the requester at submission time if their requests overlap (but not if they will actually overlap).
* In most cases it is not possible to know whether they have the true _potential_ to overlap until both requests have been approved:
  * The _actual_ start time is adjusted if the approval is after _requested_ start time so that the work can still occur within the duration specified.
  * Either issue could be accepted and the other rejected
  * The requester could be notified with more confidence (but not certainty) at the second approval point.
* It is not possible to know whether they _actually_ overlap unless they are both approved, the first is in progress, and the second start time is reached.
  * This is because the first could be revoked before the second start time is reached
  * In this scenario it would be possible to not start (reject/ignore) the second one, and notify the requester that even though it was approved then they need to resubmit it.
* It is not possible to know what the final end time will be until it is actually reached, because:
  * Either issue could be revoked while they are both in progress
  * The second could be revoked before its requested end time
* The only way to _truly_ be sure that they won't overlap is to prevent _any_ requests for the same User/Account/Role combination until the first is no longer relevant (is Ended/Rejected/Revoked).
  * The requester could be notified with certainty at submission time
  * It would be possible to reject/ignore at this point.

Whilst it may be technically possible to document the current behaviour and fix the notifications. My belief, however, is that making it easy to understand and to use in a business context should be higher on the priority list than making it easier to code.

I hope that adds enough clarity around the request, but would love to hear further feedback.
