### ISSUE TITLE
Deploying the solution with out IGW

### ISSUE THREAD

**Issue by e88z4** [aws-samples/iam-identity-center-team#107]
Hi, 

Our team have tried to deployed this solution into our corporate environment. Currently, none of our VPC has internet gateway. The only way to reach internet is by using our corporate proxy for inspection purposes. When the solution is deployed, we got an error message like below.

![image](https://github.com/aws-samples/iam-identity-center-team/assets/15828154/e01ef745-2951-44d2-b4dc-c8ef551e2262)

Is it possible to deploy this solution without IGW?

**Comment by e88z4** [comment]
no longer required

**Comment by tawoyinfa** [comment]
@e88z4 did you resolve this ?

**Comment by e88z4** [comment]
Yes, the solution is deployed with the need to access resource in our
private vpc.

All the resources are in the AWS side.
