### ISSUE TITLE
Nested Stack Deployed Failed for S3 'PutBucketPolicy' Lambda

### ISSUE THREAD

**Issue by KristinHonard** [aws-samples/iam-identity-center-team#109]
**Describe the bug**
I'm trying to deploy this solution in my development environment and I'm hitting the same error with a nested stack 'amplify-teamidcapp-main-xxxxxx-customs3bucketSecurity-xxxxxxxxxx'. 

In this stack, it has a Lambda function that assumes a role where the policy has the following S3 permissions:

- "s3:ListAllMyBuckets",
- "s3:PutBucketPolicy",
- "s3:PutBucketVersioning"

In the resource part of this statement, it lists the resource as "*". This is a problem for the 's3:PutBucketPolicy' action because it only accepts the resource type as the bucket's ARN. 

Please see: https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html#amazons3-bucket

Also, the custom resource in the template 'ConfigureAmplifyS3Bucket' does not send a signal to CloudFormation that the Lambda function has failed, so it just waits until the timeout period has passed. 

**To Reproduce**
1. Use a member account with the necessary prereqs completed
2. Deploy stack in that account
3. See the last nested stack pending 
4. Check CloudWatch Logs for specific Lambda function

**Screenshots**
![cloudwatch-error](https://github.com/aws-samples/iam-identity-center-team/assets/120122935/6f528808-1866-4ec5-abd1-8cd01921bf59)
![lambda-role-permissions](https://github.com/aws-samples/iam-identity-center-team/assets/120122935/7fb12340-c186-42c3-ad55-012641da0887)
![cloudformation-event-failed](https://github.com/aws-samples/iam-identity-center-team/assets/120122935/18456c75-3481-455e-b8c6-98067fe7a080)

**Additional context**
As recommended through the guide, I've created a dedicated account for this specific application (Non-Management account).

**Comment by astrovar** [comment]
Hi @KristinHonard , we haven't experienced this issue before. 

- I assume you created an AWS CLI profile to deploy this. Could you check what permissions this profile has? Is it Admin access?
- If your account is part of an organization, could you ensure that there are no SCPs denying this action (s3:PutBucketPolicy)?

**Comment by KristinHonard** [comment]
Hi Astrovar,

Upon further investigation, it looks like I missed a Control Tower enabled guardrail that was blocking S3:PutBucketPolicy in that account. I'm deploying this again right now and I'll let you know if I encounter another issue with that nested stack.
