### ISSUE TITLE
[Feature Request] Reduce Permissions for Amplify App

### ISSUE THREAD

**Issue by lazno** [aws-samples/iam-identity-center-team#114]
Currently the Amplify App uses a managed policy `AdministratorAccess` for its role

This is not best practice and will be an issue for any type of audit.

I realise that the Amplify App should not run in the management account, so the blast radius of this issue is reduced.

Still the usage of this managed policy is highly discouraged and violates the principle of least privilege. 

Can you pinpoint the necessary permissions needed for operating Amplify?

- iam identity center read access 
- iam identity center access for assigning/removing permission sets
- notifications
- probably repository access
- IAM read access
- .... 

im sure there are many more permissions necessary. but i don't think that amplify should be able to create IAM roles or interact with storage services like S3 and RDS.

https://github.com/aws-samples/iam-identity-center-team/blob/35ad5a7f43e84ed945d3d72d583ccc115eb9bc1d/deployment/template.yml#L42:L61

**Comment by tawoyinfa** [comment]
fix #132
