### ISSUE TITLE
[Feature Request] - AWS CloudTrail Lake to be created with one-year extendable retention pricing for cost consideration

### ISSUE THREAD

**Issue by rotoni** [aws-samples/iam-identity-center-team#117]
**Describe the bug**
Yesterday, CloudTrail Lake became available to create with [one-year extendable retention pricing option](https://aws.amazon.com/jp/about-aws/whats-new/2023/11/aws-cloudtrail-lake-pricing-option-optimized-flexible-retention/).

Please consider making this option the default for cost considerations.
https://aws-samples.github.io/iam-identity-center-team/docs/overview/cost.html

**Expected behavior**
CloudTrail Lake is created with one-year extendable retention pricing by default.

**Screenshots**

![スクリーンショット 2023-11-16 20 13 04](https://github.com/aws-samples/iam-identity-center-team/assets/5306415/44f6fb49-0ba0-460c-9d03-961e77345c75)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.6
 - Browser chrome
 - Version 119.0.6045.159（Official Build） （arm64）

**Additional context**

**Comment by Isawan** [comment]
@tawoyinfa  This is implemented in this PR here. Is this project accepting external contributions? https://github.com/aws-samples/iam-identity-center-team/pull/116

**Comment by tawoyinfa** [comment]
@Isawan  we are currently testing and reviewing the PR
