### ISSUE TITLE
[Feature Request]: Creating Eligibility Policies via DynamoDB

### ISSUE THREAD

**Issue by allan-lainch** [aws-samples/iam-identity-center-team#119]
Hello,

In order to speed up the process of setting up the TEAM app in a new organisation we tried to create eligibility policies by inserting entries directly into the DynamoDB eligibility policy table the app uses rather than have to make them all using the UI.

I can see the policies we inserted in the "Eligibility policy" menu in the admin settings, but you get "No eligible accounts/permissions found" on the request page. 

If we create the exact same policy via the UI it works.

If we note the ID of the DynamoDB item made via the UI for the same user or group you are trying to add directly, remove the UI table item and update the table item we added directly to match that ID, then that policy will start to work. In other words, inserting items into the eligibility policy table directly only seems to work if the ID of the item you are inserting matched an item for the same group or user that was created via the UI.

Is there a better way to automate the creation of eligibility policies, or is it not possible yet to do?

**Comment by tawoyinfa** [comment]
@allan-lainch  the ID of the dynamodb is the Identity Center  userId or GroupId of the entity you are creating the policy for.  You need to include this when you are updating the dynamoDB table.

Let me know if this helps.

**Comment by trickyearlobe** [comment]
@allan-lainch , this is definitely possible to do… If you didn’t figure it out yet from @tawoyinfa comments,  I already have a Python script that does it and I’m happy to share some of the code (but it’s quite tied to the Terraform code that does the SSO setup so I don’t want to publish it all).

**Comment by allan-lainch** [comment]
Hello,

Thanks for the responses, I missed that connection when first setting this up but am now using the Identity Center ID as the DynamoDB ID, which is working.

**Comment by reidca** [comment]
> @allan-lainch , this is definitely possible to do… If you didn’t figure it out yet from @tawoyinfa comments, I already have a Python script that does it and I’m happy to share some of the code (but it’s quite tied to the Terraform code that does the SSO setup so I don’t want to publish it all).

I would love to see this - The UI is very cumbersome when you have deeply nested OU structures which we have. If you could share the python code I would be very grateful.
