### ISSUE TITLE
admin/policy route stopped working if no permission set for management account

### ISSUE THREAD

**Issue by exiadbq** [aws-samples/iam-identity-center-team#12]
**Describe the bug**
Admin/policy route stopped working if no permission set for management account

**To Reproduce**
1. Go to '[Eligibility policy](https://main.xxxx.amplifyapp.com/admin/policy)'
2. If the management account doesn't use permission set to manage permission access
3. See error and empty screen
4. gql response ```{
    "data": {
        "getPermissions": null
    },
    "errors": [
        {
            "path": [
                "getPermissions"
            ],
            "data": null,
            "errorType": "Lambda:Unhandled",
            "errorInfo": null,
            "locations": [
                {
                    "line": 2,
                    "column": 3,
                    "sourceName": null
                }
            ],
            "message": "'PermissionSets'"
        }
    ]
}```
5. logged error
```
[ERROR] KeyError: 'PermissionSets'
Traceback (most recent call last):
  File "/var/task/index.py", line 61, in handler
    mgmt_ps = get_mgmt_ps()
  File "/var/task/index.py", line 43, in get_mgmt_ps
    return page["PermissionSets"]
```

**Expected behavior**
It should still have the permission sets there working on the page.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
I am not sure about the intention of the code
https://github.com/aws-samples/iam-identity-center-team/blob/526c4d92a95af7a206afd3f44ef8019091cc254c/amplify/backend/function/teamgetPermissions/src/index.py#L68
Why it needs to check management account permission sets? 
We only use a subset of the permission set for the account deploying the amplify app, and we don't use the permission set at all for our management account. 
Is there any expectation of the structure of the setup or the part of doc I didn't notice.

**Comment by tawoyinfa** [comment]
Thanks @exiadbq for pointing this out. The issue has been fixed in ba8366e. Follow the steps in the [update documentation](https://aws-samples.github.io/iam-identity-center-team/docs/deployment/update.html) to deploy the latest version

**Comment by exiadbq** [comment]
Thanks for the quick fix, I can confirm the updated one working as expected.

> TEAM by design cannot manage permission sets assigned to the management account.
Permission sets can be assigned to any account though, including management account, would that mean it requires no permission set used by the management account to be shared, e.g. the AWS managed ones such as PowerUser etc.

**Comment by tawoyinfa** [comment]
@exiadbq Yes. Permissionsets used by the management account and shared by other accounts would not be used by TEAM

> > TEAM by design cannot manage permission sets assigned to the management account.
> > Permission sets can be assigned to any account though, including management account, would that mean it requires no permission set used by the management account to be shared, e.g. the AWS managed ones such as PowerUser etc.

**Comment by tawoyinfa** [comment]
@exiadbq we'd love to hear from you. Please complete this nonobligatory [feedback form](https://forms.gle/PDis3i46XABCpSBHA). Thank you for helping us improve!
