### ISSUE TITLE
approval and access request not showing up on the TEAM console

### ISSUE THREAD

**Issue by takalumi** [aws-samples/iam-identity-center-team#128]
**Describe the bug**

When I submit access request on TEAMS, my request doesn't show up under my request. Out of about 30 attempts of trying to submit a request, only one show up under the my request tab. In addition to that, the single request doesn't display on the approval menu or send a slack notification as initially configured. I have deployed the latest image (73d780c) as displayed on the amplify settings. One other thing that is I had like to add is that I still see v1.1.0 on the TEAM console, I'm I missing something?
**To Reproduce**
Go to 'Team IDC application and submit a team request'
Click on 'Create TEAM Request'
Submit the request
As a requester click on "Create request" after submitting request, no new request is displayed under my request tab
As an approver click on "Approve Requests"
There will be no approvals available to approve.
**Expected behavior**
The request should show in the my requests window - for requester
The request should show in the approve requests window

**Screenshots**

**Additional context**
intermittent failures around access requests that did not show up in the request and approvals list 
![image](https://github.com/aws-samples/iam-identity-center-team/assets/153163843/0f5269b4-151d-4d33-8aec-e7e86447ed38)

**Comment by takalumi** [comment]
@tawoyinfa any idea pls?

**Comment by tawoyinfa** [comment]
@takalumi 
- Was the solution working previously or is this a new deployment ?
- have you made any personal modifications or changes to the TEAM code ?

without more information, It'd be difficult to ascertain the root cause of your issue as this is an isolated occurence.

**Comment by takalumi** [comment]
@tawoyinfa yes solution was working previously. The only modification I noticed was that our IT team edited the admin and auditor group name without our knowledge. Though have reverted the group name change but issue still persists.

**Comment by trickyearlobe** [comment]
I have a similar issue on a small subset of my accounts.
All requests are set for auto-approve

User requesting access sees no request in `My Requests`, but I do see in `Audit - Approvals` that there are in fact requests, but they are in pending state and they have nothing in the `Requester` field

**Comment by tawoyinfa** [comment]
@trickyearlobe are you running the latest version ?

**Comment by trickyearlobe** [comment]
Hi @tawoyinfa , not at the moment... but it's been working flawlessly till we had to assign perms for 2 additional accounts.
Thos are the only accounts having the issue.

**Comment by tawoyinfa** [comment]
@trickyearlobe i would recommend upgrading to the latest version and lets know if you still have the issue
