### ISSUE TITLE
[Feature Request] Ability to send decision logs into S3 bucket (for SIEM purposes)

### ISSUE THREAD

**Issue by rapides** [aws-samples/iam-identity-center-team#134]
**Describe the feature**
It would be great to have an optional feature that allows us to send decision logs into a S3 bucket. It would be very useful for further analysis including security audits of 3rd party tools. I know that we can always use AWS CloudTrail but it does not contain the same data as DynamoDB about access requests, approvals/rejections, justification descriptions, creating in-app policies etc. Having everything described in a consistent format in the S3 bucket would be very useful.

**Expected behavior**
1. Add an optional variable that allows the definition of an S3 bucket arn for TEAM's log storage (S3 bucket can be located in other AWS account)
2. Execute a deployment script that would provide functionality for sending the app's decision logs into a given S3 bucket (assuming that the S3 bucket has the right resource-based policy)

**Comment by taylorwilliams** [comment]
This would be very useful, great suggestion.
