### ISSUE TITLE
TEAM with Ad Sync

### ISSUE THREAD

**Issue by gabriel-rabelo-ecore** [aws-samples/iam-identity-center-team#135]
**Describe the bug**
After implementation, the TEAM page keeps loading infinitely (I tried clearing the cache and nothing) (Photo1).
I try to create a manual user in a cognito, and the same thing happens.

To Reproduce
I completed all the steps up to the deployment level.
https://aws-samples.github.io/iam-identity-center-team/docs/deployment/deployment_process.html

**Expected behavior**

Can the TEAM application work with AD Sync? 

**Screenshots**
![image](https://github.com/aws-samples/iam-identity-center-team/assets/141259398/ef68e0ab-f70b-4381-9f35-79c5e6486e34)
![image](https://github.com/aws-samples/iam-identity-center-team/assets/141259398/4a926390-74cb-4421-afef-d7bebd996982) F12 Logs
![image](https://github.com/aws-samples/iam-identity-center-team/assets/141259398/25ca51f4-5f22-4bd5-816b-18696012cfda)

**Desktop (please complete the following information):**
 - Try mozilla, google chrome

**Additional context**
Is there somewhere I can see the more detailed log??

**Comment by gabriel-rabelo-ecore** [comment]
follow the logs
![image](https://github.com/aws-samples/iam-identity-center-team/assets/141259398/21d9ca3e-2be6-426c-bd86-0850e9eb4b87)
![image](https://github.com/aws-samples/iam-identity-center-team/assets/141259398/fcdd29b0-f1c8-4aa4-8ebb-748ae10677e9)

**Comment by acavalcaws** [comment]
Hi Gabriel. Have you tried to use "group@domain" in the parameters.sh? 
When I am using AD Connector I noticed I have to specify the domain as before the deployment.

**Comment by andrecvnt** [comment]
Hi Gabriel. Have you tried to fill out the paramters.sh file with "group@domain" for the admin and auditor? 
I noticied that I have to use the domain name when using AD Connector.

**Comment by gabriel-rabelo-ecore** [comment]
-- Extra --

1- The APIs that use some association with the userId, are not returning data in a doc said the following about that error: UnknownOperationException is raised when the client request cannot be recognized by the server. This is usually caused by client trying to hit new APIs/features not supported by the server. We tried to use other APIs to retrieve the same information, but it works but does not return data.
2- In the TEAM DOC there is a very specific part that says that the integration of the Identity Center with the Application needs to be via SAML 2.0 (The TEAM application needs to be onboarded as a SAML 2.0 application on AWS IAM Identity Center before it can be fully accessed.) ... In the doc in the console itself it says that it is mandatory to use SAML 2.0 (We configured it in the Application to use SAML 2.0, while in the identity provider they use AD Sync) (Users you assign here must also have equivalent accounts in the Custom SAML 2.0 application before they can have multi-account access to the application from the AWS access portal.You can create these accounts manually or enable just-in-time (JIT) provisioning in the application to create these accounts automatically. ).

**Comment by gabriel-rabelo-ecore** [comment]
Hi @andrecvnt , i tried in paramters.sh to put it with "group@domain" and only "group" and none of them worked.


I perceived that when I Assign users or groups to TEAM application if I search for the group without the domain it finds it, and when I try to search with the domain it doesn't, that's why I did both tests.

Example:
I'm looking for the group **yellow-1**  (he finds it)
I'm looking for the group **yellow-1@adexemple** (he doesn't find it)
