### ISSUE TITLE
Notifications to Slack

### ISSUE THREAD

**Issue by kennygt51** [aws-samples/iam-identity-center-team#14]
Currently, only email is supported for notification of approval requests and approval completion.
Slack notifications will be more convenient for many users.

**Comment by tawoyinfa** [comment]
@kennygt51  We will add this to the solution roadmap

**Comment by tawoyinfa** [comment]
@kennygt51 we'd love to hear from you. Please complete this nonobligatory [feedback form](https://forms.gle/PDis3i46XABCpSBHA). Thank you for helping us improve!

**Comment by daniel-laszlo** [comment]
first of all, TEAM fills in a huge gap in the AWS ecosystem so thanks for that!

And slack notifications would be a very much needed feature from our side as well! where can i see the solution roadmap?

**Comment by tawoyinfa** [comment]
@daniel-laszlo lend your voice by completing this nonobligatory [feedback form](https://forms.gle/PDis3i46XABCpSBHA). We will use this to prioritise the solution roadmap.
