### ISSUE TITLE
Blank Page when accessing Eligibility policy

### ISSUE THREAD

**Issue by niven01** [aws-samples/iam-identity-center-team#140]
**Describe the bug**
This was already reported here https://github.com/aws-samples/iam-identity-center-team/issues/101 

After going through the deployment process in here https://aws-samples.github.io/iam-identity-center-team/docs/deployment/deployment_process.html I wanted to add eligibility policies. When i go to the page i got blank

**To Reproduce**
Steps to reproduce the behaviour:

1. Log into the application as TEAM admin.
2. In the left-hand menu go to Administration → Eligibility policy.
3. Click on Create eligibility policy 
4. Results in blank page in chrome and edge

**Expected behaviour**
Page allowing me to create Eligibility policy

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome, Edge
 -  Version 1.1.0

**Additional context**
I've seen the comment regarding Assigning a Permission set to the management account back in Oct 2023. I attempted this but still see a blank page. 

It's possible I've done this wrong

I logged into Org Management account
Opened IAM Identity Center
Created a Permission Set with AdminstratorAccess

Is there a fix in the pipeline? Can someone explain the work around using permission sets

**Comment by tawoyinfa** [comment]
@niven01 usually this is because there is no permission set assigned to the management account. Can you try  assigning a permission set to the management account and try again ?

**Comment by niven01** [comment]
Thanks I've literally just done. I had set the permissions set in the wrong account. Effectively had to do this on the master payer account and not what I deemed the managment account

I can confirm I have a work around
