### ISSUE TITLE
Deprecated lambda runtimes

### ISSUE THREAD

**Issue by pacias1** [aws-samples/iam-identity-center-team#156]
According to: https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-14-x-in-the-aws-sdk-for-javascript-v3/

Nodejs14.X runtime will be deprecated on April 30, 2024. Currently, some Lambda functions uses this runtime, most of them are created with mplify-teamidcapp-main-* cloudformation stack, which triggers creation of auth lambda functions, mostly related for AWS Cognito integration. Is there any way to upgrade runtime to nodejs18.X? I see that the definitions for these lambda functions are stored in s3 bucket amplify-teamidcapp-main-*-deployment.

**Comment by tawoyinfa** [comment]
Fixed #166
