### ISSUE TITLE
Groups cannot be displayed entirely when adding a new policy from the Eligibility Policy section on Amplify

### ISSUE THREAD

**Issue by EGHPrometeia** [aws-samples/iam-identity-center-team#16]
**Describe the bug**

teamGetIDGroup lambda function (iam-identity-center-team/amplify/backend/function/teamgetIdCGroups/src/index.py) allows to display only the first page of the group list. Therefore, if an users wanted to create an eligibility policy from the TEAM app on Amplify choosing _Group_ as Entity type, the dropdown menu would display results partially.

**To Reproduce**
1. Go to 'the Eligibility Policy' panel
2. Click on 'Entity type' and select 'Group'
3. Click on 'Group' dropdown menu to see the available groups

**Expected behavior**

In case there were more groups in your organization than those fitting one page, you wouldn't be able to see them as expected. 

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: Safari 
 - Version: 16.5

**Solution** 

We suggest the following fix to the lambda function, i.e.: 

```
from botocore.exceptions import ClientError
import boto3

def get_identiy_store_id():
    client = boto3.client('sso-admin')
    try:
        response = client.list_instances()
        return response['Instances'][0]['IdentityStoreId']
    except ClientError as e:
        print(e.response['Error']['Message'])


sso_instance = get_identiy_store_id()


def list_idc_groups(IdentityStoreId):
    try:
        client = boto3.client('identitystore')
        p = client.get_paginator('list_groups')
        paginator = p.paginate(IdentityStoreId=IdentityStoreId)
        all_groups = []
        for page in paginator:
            all_groups.extend(page["Groups"])
        return all_groups
    except ClientError as e:
        print(e.response['Error']['Message'])


def handler(event, context):
    return list_idc_groups(sso_instance)
```

**Comment by tawoyinfa** [comment]
@EGHPrometeia Thanks for spoting this. The issue has been fixed in f50c29a. There are a few other occurrences. I recommend that you update to the latest version
