### ISSUE TITLE
[Feature Request] Expiration options for eligibility/approver policies

### ISSUE THREAD

**Issue by robbycuenot** [aws-samples/iam-identity-center-team#161]
**Describe the bug**
[Feature Request] Expiration options for eligibility/approver policies.

One workflow we've found to be common is that a team says "we need a workflow set up on x accounts for the duration of this sprint". We are still in a pilot phase with this tool so this is easily maintained manually (for now). I can foresee a scenario when we start adding hundreds of policies in the future, and without expiration, the list will grow to a daunting size. Having the ability to set auto-expiration on these policies will help keep the list maintainable, in theory.

I should note, we also plain to maintain the approver / eligibility policies as code at some point, which may render this point moot or add complexity if the policies remove themselves. I haven't given the underlying DB a deep look yet, but I could imagine that having an expiration date as a field and leaving the records in place would solve this issue.

Curious what the "team" team thinks about this scenario-- maybe there is an easier way to handle this?

**Comment by tawoyinfa** [comment]
Acknowledged. This is indeed a good use case and would add to the pipeline.
