### ISSUE TITLE
Team Unable to load accounts for Access Request

### ISSUE THREAD

**Issue by dilipsun** [aws-samples/iam-identity-center-team#162]
### TEAM unable to load _Accounts

We have around 70 AWS Accounts in our environment ,TEAM is unable to load the accounts (attached screenshot) and hence we are not able to raise an access request because of the same ,This seems like an issue with Lambda which pulls the account details to TEAM application when account count is more.

Has any one come across similar issue ?

<img width="960" alt="Screenshot-Github" src="https://github.com/aws-samples/iam-identity-center-team/assets/20889304/dfc63d68-4768-4a89-a68a-393585d110de">

**Comment by robbycuenot** [comment]
I have 85 accounts and the field is definitely slow, however it loads after 5-10 seconds

**Comment by danluera** [comment]
I've not had an issue with this.  But, I'd check your Cloudwatch logs to see if there is an error popping up.  Specifically look in /aws/lambda/teamgetAccounts-main to see if there's a permission issue logged there.
