### ISSUE TITLE
Admin pages in TEAM is not displaying in browser. Blank Page

### ISSUE THREAD

**Issue by CatchKarthik** [aws-samples/iam-identity-center-team#165]
**Describe the bug**
After setting up TEAM, when trying to browse the Administrator related pages, it shows a blank page. For eligibility policy, when trying to fill the details in the popup, the popup box disappears suddenly and shows a blank page. For Settings page, it shows a blank page as soon as we access it.
**To Reproduce**
1. Login to TEAM website
2. Click on Settings menu. you will get a blank page
3. Go to Eligibility Policy. Click on Create eligibility Policy and select entity type. The pop disappears and we get a blank page

The browser provides the following error
_The resource from “https://xxxxxxxx.amplifyapp.com/index.html” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)._

**Expected behavior**
The website should display properly without errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome, safari, Firefox
 - Version : 1.1.0 and 1.1.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GeoDia** [comment]
Exactly same problem here! It happens only for the eligibility policy.
