### ISSUE TITLE
Feature request: Support machine authentication without static credentials

### ISSUE THREAD

**Issue by lukasgabi** [aws-samples/iam-identity-center-team#167]
**Describe the bug**
The AWS AppSync API is currently only available throught Cognito user pools. The option currently provided to get machine access is to create a resource server and create static credentials (client_id, client_secret). To follow security best practices, static credentials should be avoided.

**Proposed solution**
If the automation is running within AWS, aws_iam could be used to configure API access. It is already enabled on the AWS AppSync as an authorization provider, however admin access is currently restricted to specific ARNs. It seems that this is not explicitly configured anywhere, so this might be an AWS Amplify limitation.

**Alternatives**
- Use provided machine authentication and set up custom secrets rotation, i.e. with secrets manager

**Comment by vinnymachacek** [comment]
https://github.com/aws-samples/iam-identity-center-team/blob/bdd7cd6c1a213bbd06b21888635cd2d399d4770d/amplify/backend/api/team/schema.graphql#L123 I wonder if the issue with the operations listed.  I think Create and Delete are missing

**Comment by lukasgabi** [comment]
It seems that one of the main restrictions is the amplify generated auth function (example taken from MutationcreateEligibilityauth0Function), specifically this section:
```
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $inputFields = $util.parseJson($util.toJson($ctx.args.input.keySet())) )
#set( $isAuthorized = false )
#set( $allowedFields = [] )
#if( $util.authType() == "IAM Authorization" )
  #set( $adminRoles = ["teamNotifications-main","teamRouter-main","teamStatus-main","teamgetGroups-main","teamgetLogs-main","teamgetUserEntitlement-main","teamgetUsers-main"] )
  #foreach( $adminRole in $adminRoles )
    #if( $ctx.identity.userArn.contains($adminRole) && $ctx.identity.userArn != $ctx.stash.authRole && $ctx.identity.userArn != $ctx.stash.unauthRole )
      #return($util.toJson({}))
    #end
  #end
$util.unauthorized()
...
```
These probably get generated in the function configuration, i.e. teamRouter:
https://github.com/aws-samples/iam-identity-center-team/blob/bdd7cd6c1a213bbd06b21888635cd2d399d4770d/amplify/backend/function/teamRouter/function-parameters.json#L2-L9
