### ISSUE TITLE
Conflicting max duration when two groups have eligibility on same permission set

### ISSUE THREAD

**Issue by caspar-ds** [aws-samples/iam-identity-center-team#171]
**Describe the bug**
If two groups have eligibility to raise a request for the same permission set and both have different max durations, the request will fail with an error - the lowest duration is taken as the max.

**To Reproduce**
1. Given groups A and B
2. Set up an eligibility policy for group A on permission set X with max duration of 2 hours
3. Set up an eligibility policy for group B on permission set X with max duration of 4 hours
4. Add a user to group A and group B
5. User raises a request for permission set X with a duration of 4 hours
6. The request will fail with an error

**Expected behavior**
The user should be able to raise a request with a duration up to 4 hours - the greater of the two eligibility policies that apply to the groups of which they are a member

**Screenshots**
N/A

**Additional context**
- Version: v1.1.0

**Comment by tawoyinfa** [comment]
@caspar-ds  let me know if this issue has been fixed for you
