### ISSUE TITLE
teamListGroups returns members of first group only

### ISSUE THREAD

**Issue by jarrod-mg** [aws-samples/iam-identity-center-team#176]
I am trying out TEAM, and have found that I cannot raise a request for access if I am an approver for the account I am requesting access to - even though there are other possible approvers.

This means we can't have "peer approvals" - I can't set it up so I can approve a request for one of my colleagues, while they can also approve my access.

It makes sense that I can't approve my own requests, but I should be able to raise a request when I am in the group (or one of the groups) that can approve requests on that account, so someone else can approve it.

**Comment by jarrod-mg** [comment]
On further investigation, it appears as if this _should_ be supported; but isn't because of a bug.

In teamListGroups, the handler will return the members of the _first_ group with _any_ members. 

```
    members = []
    groupIds = event["arguments"]["groupIds"]
    for groupId in groupIds:
        if members:
            return {"members": members}
        members.extend(list_idc_group_membership(groupId))
    return {"members": members}
```

In my case, the first group returned one entry - me, and the second group would have returned a bunch more.

This code will, on the first time through the groupIds loop, add the members of the first group to the members list. On the second, it will detect that members is not empty, and return before getting the members of the second group. I think you just need to remove the `if members: return { ... }` bit?

**Comment by tawoyinfa** [comment]
@jarrod-mg  thanks for point this out. Let me know if you still face this issue after this update
