### ISSUE TITLE
Cannot display session activity logs when username contains capital letters

### ISSUE THREAD

**Issue by jyrkiput** [aws-samples/iam-identity-center-team#18]
**Describe the bug**
When username in AWS IAM Identity Center contains capital letters, the session activity logs aren't displayed. 

**To Reproduce**
1. Create user in IAM Identity Center with name containing capital letters, for example "TEAMuser"
2. Activate session with TEAM
3. Do something in session
4. Check session activity logs and see "No logs/No logs to display"

**Expected behavior**
Logs should be visible

**Additional context**
Cause for this seems to be the way that Cognito userpools handles usernames with SAML 2.0 identity providers. According to the documentation, Cognito prepends the IdP name to the username provided by IdP, but it seems that in addition to this the whole combination of IdP name + username are made to lower case.

I verified this behaviour by modifying the query used to fetch the session activity logs by adding "lower" to the query, (`lower(useridentity.principalId) LIKE '%:${username}%'`) 

So I changed the https://github.com/aws-samples/iam-identity-center-team/blob/f50c29a18299f6a48c4cc203dbe3bc2374f7a43f/amplify/backend/function/teamgetLogs/src/index.js#L144 to be

```
const input = {
      QueryStatement: `SELECT eventID, eventName, eventSource, eventTime FROM ${EventDataStore} WHERE eventTime > '${startTime}' AND eventTime < '${endTime}' AND lower(useridentity.principalId) LIKE '%:${username}%' AND useridentity.sessionContext.sessionIssuer.arn LIKE '%${role}%' AND recipientAccountId='${accountId}'`,
    };
```

The other option would be creating a new attribute mapping in Identity Center for the application of (for example `PreferredUsername - ${user:subject} - basic` ) and using that instead of username from Cognito.

**Comment by tawoyinfa** [comment]
@jyrkiput good call out. I like the first option. Can you create a pull request for this change and i can test and merge it afterwards. Thanks
