### ISSUE TITLE
Feature Request: Ability to Infra As Code Approval/EIigibility Policies

### ISSUE THREAD

**Issue by othmane399** [aws-samples/iam-identity-center-team#181]
**Describe the issue**
Today the only way to manage Approval/EIigibility Policies is by logging to the app and create/edit them via the Web console.

**Describe the feature you would like to have implemented.**
Ability to use some Infra as Code tools as Terraform or just a JSON format so we can manage theses policies from a Git repo and have some peer reviews, CI/CD controls on that

**Comment by brittandeyoung** [comment]
@othmane399 I developed and maintain a terraform provider for [awsteam](https://registry.terraform.io/providers/brittandeyoung/awsteam/latest).

**Comment by othmane399** [comment]
> @othmane399 I develop and maintain a terraform provider for [awsteam](https://registry.terraform.io/providers/brittandeyoung/awsteam/latest).
> 
> github repo: https://github.com/brittandeyoung/terraform-provider-awsteam

oh great ! thanks for that !
