### ISSUE TITLE
AmplifyRole is overly permissive

### ISSUE THREAD

**Issue by billyjbryant** [aws-samples/iam-identity-center-team#19]
**Describe the bug**
The AmplifyRole that is required by the TEAM App utilizes the `AdministratorAccess` IAM Policy with arn `arn:aws:iam::aws:policy/AdministratorAccess`. This policy is overly permissive and should be used sparingly. 

**To Reproduce**
1. Proceed to deploy the Amplify solution.
2. Evaluate access for the IAM resources created. 

https://github.com/aws-samples/iam-identity-center-team/blob/f50c29a18299f6a48c4cc203dbe3bc2374f7a43f/deployment/template.yml#L45

**Expected behavior**
The Amplify role should either include an inline policy or create a managed policy that specifies the exact permissions required to operate the TEAM Application. 

**Screenshots**

**Desktop (please complete the following information):**
 - n/a

**Smartphone (please complete the following information):**
 - n/a

**Additional context**
Utilizing the AdministratorAccess policy here is an oppertunity for privsec violations. This policy should be sparingly used and this application shouldn't require it.

**Comment by tawoyinfa** [comment]
@billyjbryant good point.
However note that Amplify in this context is a deployment tool that abstracts cloudformation templates used to build the backend and host the frontend of the TEAM application. The cloudformation templates which can be found [here](https://github.com/aws-samples/iam-identity-center-team/tree/main/amplify/backend) are all serverless resources scoped and locked down with their own least-privileged roles. TEAM( broker and other resources) does not run using admin but well-scoped least privileged roles.
Check the [security consideration section](https://aws-samples.github.io/iam-identity-center-team/docs/overview/security.html#general) for more information on best practice for securing your TEAM implementation.

**Comment by billyjbryant** [comment]
> However note that Amplify in this context is a deployment tool that abstracts cloudformation templates used to build the backend and host the frontend of the TEAM application.

We should still insist on least privilege wherever possible. It isn't too difficult to extrapolate what permissions the role needs in order to deploy the subsequent stacks successfully, then right-sizing it accordingly.
