### ISSUE TITLE
Feature Request: Continous Testing

### ISSUE THREAD

**Issue by jarrod-mg** [aws-samples/iam-identity-center-team#190]
Hi,

We have had an issue where an upgrade broke TEAM. I can imagine a lot of things that _could_ go wrong - and that there a lot of things I haven't thought of, too.

To give me confidence, I'd love to have some continuous (e.g. hourly) test, that tests the system end-to-end, without impacting anyone. It would then raise an alert (cloudwatch alarm, sns message, something...) that I could plumb into our monitoring and alerting systems to tell me there is an issue.

However, I am unsure of how to go about this. Do you have such a system already? How would one even work?

**Comment by sbrown-tecracer** [comment]
I think this could fall onto a deployment approach of having say a DEV / Stage & Prod environment, especially for 3rd Party Solutions like TEAM so that these findings a "reduced" instead of a big-bang approach?
