### ISSUE TITLE
Feature Request: Slackbot to channel

### ISSUE THREAD

**Issue by jarrod-mg** [aws-samples/iam-identity-center-team#191]
Hi,

We are using the slackbot integration. It currently sends a private DM to every member of the approval groups relevant to the request.

This results in multiple people responding to the request, taking a look and checking out the ticket - only to discover someone else has already approved the request.

It would be great if we could configure the slackbot to send to a slack channel instead. That way, we can surround the approval mechanism with a simple bit of policy (e.g. use the 👀 emoji to indicate that you have picked up looking into the request, and everyone else can ignore it).

Sending them all to a single channel would work, but it would be better if we could set up an OU to channel mapping.

**Comment by sbrown-tecracer** [comment]
I would also support this feature.
To note, Slack-App from AWS when used can ensure that a Slack Channel is used for communication instead of PM's which maybe the Feature could base the workings from this?
But a Vote from me 👍

**Comment by evets51** [comment]
This would help us meet our requirement of having a small group of approvers but a much larger group of people who received notification for approval requests who could then ensure the relevant people actioned them.

**Comment by ehastings-lotame** [comment]
So does adding this comment re-open this and get it attention? In any case - yes, this is a no-brainer. The DM approach makes team-based handling of requests require extra coordination.

**Comment by ccioltan** [comment]
We also need to be able to send all TEAM Slack notifications to a Slack channel.
Can you please help with this?

**Comment by Dragos08** [comment]
Hello, any news about this? We would really appreciate this feature since we're in great need to send TEAM notifications directly to slack channels.
