### ISSUE TITLE
Can't log into TEAM

### ISSUE THREAD

**Issue by ivo-sudo** [aws-samples/iam-identity-center-team#194]
**Describe the bug**
The application has been deployed, SAML configuration steps have been completed as per docs. App is showing as active in IAM Identity Centre. Cognito config script also appears to have completed successfully and 'IDC' is showing as an identity provider in the Cognito Console.
However once I open the TEAM app I get the loading wheel spinning and after circa 20 secs it goes back to the screen below. 
![Image 05-03-2024 at 12 22](https://github.com/aws-samples/iam-identity-center-team/assets/67359432/d866996b-96da-4e4c-bee7-a465c5b2d581)

Clicking on the blue button brings up an error message: "An error was encountered with the requested page".

CloudTrail logs:

{
    "eventVersion": "1.09",
    "userIdentity": {
        "accountId": "1234567890"
    },
    "eventTime": "2024-03-05T12:15:21Z",
    "eventSource": "cognito-idp.amazonaws.com",
    "eventName": "Token_POST",
    "awsRegion": "eu-west-2",
    "sourceIPAddress": "2a00:23c6:456c:3201:1234:d953:b123:000",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "errorCode": "400",
    "requestParameters": null,
    "responseElements": null,
    "additionalEventData": {
        "responseParameters": {
            "status": 400
        },
        "requestParameters": {
            "code": [
                "HIDDEN_DUE_TO_SECURITY_REASONS"
            ],
            "grant_type": [
                "authorization_code"
            ],
            "redirect_uri": [
                "https://portal.teamtest.online/"
            ],
            "client_id": [
                "17qirpllb0r7fpt90qge2jkab1"
            ]
        },
        "userPoolDomain": "domain-main.auth.eu-west-2.amazoncognito.com",
        "userPoolId": "eu-west-2_ABCDEFG"
    },
    "requestID": "0448d186-82e6-4afa-97fb-7098c7331d62",
    "eventID": "56a37d4e-79fc-412e-95e9-6342fdefed9b",
    "readOnly": false,
    "eventType": "AwsServiceEvent",
    "managementEvent": true,
    "recipientAccountId": "1234567890",
    "serviceEventDetails": {
        "serviceAccountId": "500792760757"
    },
    "eventCategory": "Management",
    "tlsDetails": {
        "tlsVersion": "TLSv1.3",
        "cipherSuite": "TLS_AES_128_GCM_SHA256",
        "clientProvidedHostHeader": "domain-main.auth.eu-west-2.amazoncognito.com"
    }
}

**Comment by tawoyinfa** [comment]
@ivo-sudo did you include UI_DOMAIN=portal.teamtest.online in your parameters.sh file ?

**Comment by ivo-sudo** [comment]
As I understand it, this parameter is optional so I've left it as the default value. I think it's what I did the last time I deployed TEAM. Should I have done something else?

**Comment by tawoyinfa** [comment]
@ivo-sudo  you need to remove it from your parameters.sh file and redeploy the solution.  You should only add it if you are actually planning to use a custom domain of yours.

**Comment by ivo-sudo** [comment]
Thank you so much for your help!

**Comment by AlexHasMe** [comment]
Hi @tawoyinfa! I have the similar issue but I didn't include UI_DOMAIN variable in parameters.sh when deployed the stack. When I click on an APP icon in aws sso starting page I get `An error was encountered with the requested page.`
In cloudtrail I see such log
```
{
    "eventVersion": "1.09",
    "userIdentity": {
        "accountId": "xxx"
    },
    "eventTime": "2025-04-21T10:33:13Z",
    "eventSource": "cognito-idp.amazonaws.com",
    "eventName": "Token_POST",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "x.x.x.x",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.4 Safari/605.1.15",
    "errorCode": "400",
    "requestParameters": null,
    "responseElements": null,
    "additionalEventData": {
        "responseParameters": {
            "status": 400
        },
        "clientId": "xxx",
        "requestParameters": {
            "code": [
                "HIDDEN_DUE_TO_SECURITY_REASONS"
            ],
            "grant_type": [
                "authorization_code"
            ],
            "redirect_uri": [
                "https://main.d1s5ncogc730zk.amplifyapp.com/"
            ],
            "client_id": [
                "xxx"
            ]
        },
        "userPoolDomain": "d1s5ncogc730zk-main.auth.us-west-2.amazoncognito.com",
        "userPoolId": "us-west-2_xxx"
    },
    "requestID": "e9dcb783-145f-492f-a5ee-867d7d6685b6",
    "eventID": "6aa0e40c-626e-4133-ab80-215138fc1b59",
    "readOnly": false,
    "eventType": "AwsServiceEvent",
    "managementEvent": true,
    "recipientAccountId": "xxx",
    "serviceEventDetails": {
        "serviceAccountId": "xxx"
    },
    "eventCategory": "Management",
    "tlsDetails": {
        "tlsVersion": "TLSv1.3",
        "cipherSuite": "TLS_AES_128_GCM_SHA256",
        "clientProvidedHostHeader": "d1s5ncogc730zk-main.auth.us-west-2.amazoncognito.com"
    }
}
```

Also I have a question about this domain `"https://main.d1s5ncogc730zk.amplifyapp.com/"`. It's not mine and it's configured here https://github.com/aws-samples/iam-identity-center-team/blob/main/amplify/backend/auth/team06dbb7fc/cli-inputs.json. Is it correct that I got redirected to this domain? Thanks.
