### ISSUE TITLE
The user is able to access the AWS resources even though the access has been revoked

### ISSUE THREAD

**Issue by mukherarn1** [aws-samples/iam-identity-center-team#195]
Issue Description: The user is able to access the AWS resources even though the access has been revoked. The user was provided with Admin access and logged into the account. However, I have revoked the access but he's still able to access AWS resources as the session is still active

**Expected behavior**
Once the access is revoked, the user shouldn't be able to perform any actions

**Comment by tawoyinfa** [comment]
Refer to the documentation on this - 
https://aws-samples.github.io/iam-identity-center-team/docs/overview/security.html#elevated-access-and-session-duration
