### ISSUE TITLE
Region is not being added to a number of the aws cli commands causing issues

### ISSUE THREAD

**Issue by reidca** [aws-samples/iam-identity-center-team#199]
**Describe the bug**
The parameters.sh file accepts a region parameter however this parameter is not always used in all of the aws cli commands causing errors in various places.

Examples:

[deployment](https://github.com/aws-samples/iam-identity-center-team/tree/main/deployment)
/cognito.sh
```
amplifyAppId=`aws amplify list-apps --output json | jq -r '.apps[] | select(.name=="TEAM-IDC-APP") | .appId'`
amplifyDomain=`aws amplify list-apps --output json | jq -r '.apps[] | select(.name=="TEAM-IDC-APP") | .defaultDomain'`
...
amplifyCustomDomains=`aws amplify list-domain-associations --app-id $amplifyAppId --output json`
```

[iam-identity-center-team](https://github.com/aws-samples/iam-identity-center-team/tree/main)/[deployment](https://github.com/aws-samples/iam-identity-center-team/tree/main/deployment)
/integration.sh
```
amplifyAppId=`aws amplify list-apps --output json | jq -r '.apps[] | select(.name=="TEAM-IDC-APP") | .appId'`
amplifyDomain=`aws amplify list-apps --output json | jq -r '.apps[] | select(.name=="TEAM-IDC-APP") | .defaultDomain'`
...
amplifyCustomDomains=`aws amplify list-domain-associations --app-id $amplifyAppId --output json`
```

This means that the cli will use the default region associated with the profile which is not always correct. The result is that the correct amplify app is not found. What makes this worse is the error is silent leading to a misconfiguration.

**Comment by reidca** [comment]
Before the issue is closed is anyone from the maintainers going to comment?

**Comment by tawoyinfa** [comment]
@rekejarikre can you help with this ?
