### ISSUE TITLE
[Feature Enhancement] Add ability to send notices with SNS instead of SES

### ISSUE THREAD

**Issue by billyjbryant** [aws-samples/iam-identity-center-team#20]
### Description

For my organization's needs, it would be better if we can have an option to send notices via SNS, so that we can leverage a Lambda Function to create a Ticket in our Ticketing system instead of sending an email. 

I would envision seeing this as a dropdown option in the Settings of the application, during the configuration of an Approval Policy or potentially as a pre-configuration option during the deployment phase.

**Comment by tawoyinfa** [comment]
@billyjbryant this is a good suggestion which we have been working on in the background. I would upload a roadmap document that indicated features such as this that would be included in the future.

**Comment by rapides** [comment]
Totally agree. It would be great to have possibility to integrate with Slack using SNS. That's more efficient nowadays rather than emails.

**Comment by billyjbryant** [comment]
@tawoyinfa any update on where this lies in your roadmap?

**Comment by SebRosander** [comment]
+1 with Slack/Teams via SNS.

**Comment by mattcenis** [comment]
+1 with Slack/Teams via SNS.

**Comment by tawoyinfa** [comment]
This feature is included in the latest release v1.1.0
