### ISSUE TITLE
Feature request: Auditor overviews for admins

### ISSUE THREAD

**Issue by fatbasstard** [aws-samples/iam-identity-center-team#207]
**Describe the bug**
An administrator member does have the [Auditor](https://aws-samples.github.io/iam-identity-center-team/docs/guides/auditor.html) functionality available. 

Not sure if there is a specific reason for this, but as an administrator I expected to also have the request/approval history available.

**Comment by maunzCache** [comment]
I personally would not expect this. An administrator should only be able to configure the app. If you want the administrator to be also an auditor just put this person into the auditors group. I think it is a nice separation of concerns.
