### ISSUE TITLE
Error with TEAM portal not loading 

### ISSUE THREAD

**Issue by securityquest** [aws-samples/iam-identity-center-team#212]
https://main.d1ga660566c672.amplifyapp.com/static/media/Home.fa54de9b326fa07ff2d54a33f32c2697.svg

Uncaught (in promise) TypeError: e is undefined
    h App.js:77
    promise callback*Qq/h/< App.js:77
    promise callback*h App.js:74
    Qq App.js:70
    Fl React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    M scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    7234 scheduler.production.min.js:12
    Webpack 10

**Comment by securityquest** [comment]
We have Azure Ad integrated with identity center as our IDP. This issue occurs after the TEAM solution  has been successfully deployed. We think something to do with attribute mapping but not sure.

**Comment by SachinCldCvr** [comment]
You can put some print statements in between if you are still struggling with the issue. 
I had the similar issue as my UI was loading n loading, having the similar exception along with having error Fetching group ids so after putting some debugging in between, found that it was not able to fetch the groups and relevant information.
Mine was integrated with the Jumpcloud.
