### ISSUE TITLE
The Management Account is not under the Eligible Accounts list

### ISSUE THREAD

**Issue by harry1C-cw** [aws-samples/iam-identity-center-team#214]
**Describe the bug**

I would like users to be able to request elevated access to my organisation's management account. However, this account is not showing within the list of eligible accounts when attempting to create an Eligibility Policy

**To Reproduce**
1. Click on Eligibility Policy
2. Click "Add Policy" button
3. Search for "Mgmt Account Name" in Accounts drop down
4. Unable to find "Mgmt Account Name"

**Expected behavior**
The Management account is able to be selected under the List of Eligible Accounts

**Screenshots**
![image](https://github.com/aws-samples/iam-identity-center-team/assets/91198057/23096190-babe-463a-87e4-4cd75e2d6a08)

**Context**
I understand TEAM is not designed to do this. However, for organisations with management accounts that may not be following best practices. It would be helpful to be able to manage privileged access in this account

**Comment by reidca** [comment]
I would strongly advise not doing this - the management account should be handled separately.  The people with access to it should be very tightly controlled and have the correct experience and knowledge to work with such a highly privileged account. If the management account has been used for workloads my best advice is to start migrating these out to member accounts otherwise you will find yourself in a security nightmare.

**Comment by harry1C-cw** [comment]
There are some resources i.e. CfCT that need to be deployed into the managment account and managed by our teams, it would be preferable to have the ability to temporarily grant access to these resources (even for "admins") rather than having permanent access.

**Comment by tawoyinfa** [comment]
as @reidca has explained leveraging TEAM for management account access is an anti-pattern. However in cases where this is required, refer to the documentation on [Deploying TEAM into management account](https://aws-samples.github.io/iam-identity-center-team/docs/deployment/deployment_process.html#deploying-team-into-management-account)
