### ISSUE TITLE
Updating Stack Parameters does not propagate to Step Functions

### ISSUE THREAD

**Issue by billyjbryant** [aws-samples/iam-identity-center-team#22]
**Describe the bug**
If you update the stack and provide new parameters for `Source`, `Login`, `teamAdminGroup` and `teamAuditGroup`, the stack updates but the step functions are not updated accordingly as the template that deploys the Step functions via stackset is not re-generated and deployed. 

**To Reproduce**
1. Deploy the stack using CDK's `CfnInclude` functionality
2. Update the parameters passed to the stack after initial deployment
3. Validate that the parameters have not been updated in the application post-update deployment. 

**Expected behavior**
Any update to the parameters in the stack should trigger a reactionary deployment that updates all functions accordingly. 

**Screenshots**

**Additional context**

The complication to this is that I am deploying the stack by including into a CDK app using [`cdk.CfnInclude`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.CfnInclude.html), so there may be a disconnect here that is preventing the follow-up deployment.

**Comment by tawoyinfa** [comment]
@billyjbryant updating the stack paramater will not result in a change in the step function definition. The step function will be updated only when there is an actual change in the state machine definition. 

I am keen to see how are deploying the stack/solution in a CDK app. Is there a reason you are not using the existing deployment process ?

Also not that there is a [script](https://github.com/aws-samples/iam-identity-center-team/blob/main/parameters.js) that is built into the amplify pipeline that updates the stack paramaters during deployment.

**Comment by billyjbryant** [comment]
> I am keen to see how are deploying the stack/solution in a CDK app.

in my initial deployment, I used `CfnInclude` to include the Cloudformation Template into my CDK App. In my second deployment, I have completely re-written the Cloudformation Template as a CDK App. 

> Is there a reason you are not using the existing deployment process ?

Yes, our organization prefers CDK as we can abstract permissions. IE I can permit a user to assume a CDK Role that will allow deploying the CDK Stack but not have to give direct permissions to deploy the CFN Template natively etc. It also allows for analyzing CFN Template structure and adherence to best practices by implementing `cfn-nag` into the CDK App.

**Comment by jasonbrd** [comment]
Supporting updates to the `teamAdminGroup` and `teamAuditGroup` may be useful to customers if groups need to change without destroying the environment, defined policies, audit history etc.

**Comment by tawoyinfa** [comment]
@jasonbrd can you raise this as a feature request and we can prioritize this accordingly.
