### ISSUE TITLE
Guidance for Eligibility & Approval policies.

### ISSUE THREAD

**Issue by kp2401075** [aws-samples/iam-identity-center-team#225]
# Problem statement.
We are trying to deploy  this in an environment where there are large number of groups each is meant to have different level of access to different accounts.
For example below.
Eligibility policy
Group1 -> Acount 1(Developer), Account2(View-Only), Account3(Billing)
Group2 -> Acount 3(Developer), Account4(View-Only), Account5(Billing)
Approver policy
Group3 -> Acount 1, Account2
Group4 -> Acount 3 Account4. Account5

we would like to have this mapping stored in a config file somewhere in git repo and deploy it as Eligibility Policy / Approval for TEAM app via CI/CD or an automatic process.

Is there existing solution for above mentioned problem? 

We would like to avoid ClickOps.

**Comment by carlaabanes** [comment]
Hi @kp2401075 

Im curious to know if you are having problems with navigating to Administration menu on the left side and the click on Eligibility policy?
From my end, this page does not load.

Thank you.

**Comment by powerfei** [comment]
Hi, @kp2401075 , do you know why I only have one role (ReadOnlyAccess) available? How to configure it to add more options?
![image](https://github.com/aws-samples/iam-identity-center-team/assets/125493459/0c1ea3ad-f095-4c7e-9771-3280190b430b)
