### ISSUE TITLE
Upgrading botches login completely - TEAM is unusable

### ISSUE THREAD

**Issue by PeterBengtson** [aws-samples/iam-identity-center-team#228]
**Describe the bug**
We have an installation of TEAM which has worked flawlessly for over a year. Today, upgrading to the latest version according to the instructions in the repo makes it impossible to login. Instead I get an error box saying "Login option is not available. Please try another one". Trying to log in from the Amplify console has an entirely different behaviour. (see screenshots below)

As I said, nothing has been changed or modified since installation. All we have done is update TEAM. Logging out and in again doesn't fix the problem. We are now completely shut out of JIT access possibilities.

Grateful for any input or ideas.

**To Reproduce**
Just install the latest version.

**Expected behavior**
When I click the TEAM application in the AWS access portal, I expect to be logged in to the TEAM application, just as before.

**Screenshots**
This is how the normal login TEAM application presents itself:

<img width="1001" alt="Screenshot 2024-04-21 at 15 34 55" src="https://github.com/aws-samples/iam-identity-center-team/assets/3897/19deb5d3-2b9a-4547-ae66-ec62a753310e">

However, clicking on it produces this:

<img width="402" alt="Screenshot 2024-04-21 at 15 34 59" src="https://github.com/aws-samples/iam-identity-center-team/assets/3897/de78ae3d-55d4-4890-abcf-510b696a7dc6">

.. but gives an error like so:

<img width="399" alt="Screenshot 2024-04-21 at 15 35 00" src="https://github.com/aws-samples/iam-identity-center-team/assets/3897/17477aca-6174-4466-af2d-56f99e8664eb">

Trying to log in from the Amplify console, here:

<img width="1322" alt="Screenshot 2024-04-21 at 15 35 15" src="https://github.com/aws-samples/iam-identity-center-team/assets/3897/dd10fd1c-0ff1-4832-a0d8-18a8b1db5e6e">

... instead takes us to the TEAM login screen with no further autodirect:

<img width="915" alt="Screenshot 2024-04-21 at 15 35 19" src="https://github.com/aws-samples/iam-identity-center-team/assets/3897/b0922fe6-5a53-468b-8dfb-e312b01468b2">

... and clicking federated sign-in produces this:

<img width="390" alt="Screenshot 2024-04-21 at 15 35 23" src="https://github.com/aws-samples/iam-identity-center-team/assets/3897/3a4ed1eb-ba0b-4614-96b4-278079eb16c5">

... which indicates to me that something is amiss with Cognito.

The application hasn't been modified in any way. The parameter file contains entries for everything except the custom domain (we don't use one):

<img width="135" alt="Screenshot 2024-04-21 at 15 41 58" src="https://github.com/aws-samples/iam-identity-center-team/assets/3897/d2dff4c8-2dee-4198-a1ca-9d2e0c72d7ab">

**Comment by caspar-ds** [comment]
@PeterBengtson Did you find a solution to this? We are having the same issue and rolling back doesn't help

**Comment by maxzcxu** [comment]
@caspar-ds I got the same issue, I solved it by manually configure IDC as the SAML provider for cognito app client, otherwise you cannot authN with IDC. If you have ran the script `cognito.sh` you may got the validation error and fail to configure the IDC as SAML provider, and there is a [workaround ](https://github.com/aws/aws-cli/issues/2894). You can run the command below to fix the issue
```
aws cognito-idp update-user-pool-client --region $REGION --user-pool-id $cognitoUserpoolId \
--client-id $clientID \
--refresh-token-validity 1 \
--supported-identity-providers IDC \
--allowed-o-auth-flows code \
--allowed-o-auth-scopes "phone" "email" "openid" "profile" "aws.cognito.signin.user.admin" \
--logout-urls '["https://$amplifyDomain/"]'  \
--callback-urls '["https://$amplifyDomain/"]' \
--allowed-o-auth-flows-user-pool-client
```
