### ISSUE TITLE
Build fails - error: invalid command 'egg_info'

### ISSUE THREAD

**Issue by rapides** [aws-samples/iam-identity-center-team#23]
**Describe the bug**
My build fails in AWS Amplify.

> ...
> 2023-06-27T19:44:36.865Z [INFO]: Installing dependencies from Pipfile.lock (6974cb)...
> 2023-06-27T19:44:37.662Z [WARNING]: created virtual environment CPython3.8.0.final.0-64 in 2094ms
>                                     creator CPython3Posix(dest=/root/.local/share/virtualenvs/teamgetMgmtAccountDetails-aAYUwG8X, clear=False, no_vcs_ignore=False, global=False)
>                                     seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
>                                     added seed packages: pip==23.1.2, setuptools==67.8.0, wheel==0.40.0
>                                     activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
> 2023-06-27T19:44:37.668Z [WARNING]: ✔ Successfully created virtual environment!
> 2023-06-27T19:44:37.811Z [WARNING]: Virtualenv location: /root/.local/share/virtualenvs/teamgetMgmtAccountDetails-aAYUwG8X
> 2023-06-27T19:44:37.934Z [INFO]: Installing dependencies from Pipfile.lock (e02f68)...
> 2023-06-27T19:44:38.111Z [WARNING]: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>                                     or: setup.py --help [cmd1 cmd2 ...]
>                                     or: setup.py --help-commands
>                                     or: setup.py cmd --help
>                                     error: invalid command 'egg_info'
> 2023-06-27T19:44:38.134Z [WARNING]: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>                                     or: setup.py --help [cmd1 cmd2 ...]
>                                     or: setup.py --help-commands
>                                     or: setup.py cmd --help
>                                     error: invalid command 'egg_info'
> 2023-06-27T19:44:38.134Z [WARNING]: 
> 2023-06-27T19:44:38.149Z [WARNING]: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>                                     or: setup.py --help [cmd1 cmd2 ...]
>                                     or: setup.py --help-commands
>                                     or: setup.py cmd --help
>                                     error: invalid command 'egg_info'
> 2023-06-27T19:44:38.157Z [WARNING]: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>                                     or: setup.py --help [cmd1 cmd2 ...]
>                                     or: setup.py --help-commands
>                                     or: setup.py cmd --help
>                                     error: invalid command 'egg_info'
> 2023-06-27T19:44:38.656Z [WARNING]: ✖ There was an error initializing your environment.
> 2023-06-27T19:44:38.658Z [INFO]: 🛑 Command failed with exit code 1: pipenv install
>                                  Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
> 2023-06-27T19:44:38.758Z [INFO]: 
> 2023-06-27T19:44:38.758Z [INFO]: Session Identifier: afbe16a3-6fb0-49fe-8647-2ceab3d9709e
> 2023-06-27T19:44:38.840Z [ERROR]: !!! Build failed
> 2023-06-27T19:44:38.841Z [ERROR]: !!! Non-Zero Exit Code detected
> 2023-06-27T19:44:38.841Z [INFO]: # Starting environment caching...
> 2023-06-27T19:44:38.841Z [INFO]: # Environment caching completed
> Terminating logging...

**To Reproduce**
Steps to reproduce the behaviour:
1. Execute `./deploy.sh` with success
2. Check AWS Amplify if everything has been deployed with success
3. Build failed

**Expected behaviour**
Build should not be failed.

**Screenshots**
<img width="1592" alt="image" src="https://github.com/aws-samples/iam-identity-center-team/assets/2733755/11c326ea-d328-41fb-a222-2f2ffa7e7614">

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Comment by tawoyinfa** [comment]
It looks like there is an issue with the latest version of pipenv(2023.6.26) which is used by the Amplify build pipeline to package the backend python lambda functions. I have updated the buildspec to use the most recent stable version of pipenv(2023.6.12).
Try deploying the latest commit and let me know if it fixes the problem for you.

**Comment by rapides** [comment]
@tawoyinfa It worked for me, thanks! 🎉
