### ISSUE TITLE
Intermittent issue || Not able see Requester's request when logged as Approver.

### ISSUE THREAD

**Issue by banagevikas** [aws-samples/iam-identity-center-team#230]
**Describe the bug**
We have implemented this for one of the customer 1 year back. It was working fine till end Feb.
Since March users (who have access as Approvers) were reporting issue : they not able to see request when someone elevated access has been requested. 

**To Reproduce**
Since this is intermittent issue, not able to replicate easily
Request for Elevated Access --> Check if Approver able to see request.

**Expected behavior**
Approver Should able see request. 

**Screenshots**
<img width="1232" alt="Requester" src="https://github.com/aws-samples/iam-identity-center-team/assets/73884075/71f3b6bc-8f6f-4ca2-9fe6-32356562a80d">

<img width="1436" alt="Apprver-Screen" src="https://github.com/aws-samples/iam-identity-center-team/assets/73884075/5ae40795-d8f3-493c-b1a2-34cd74d763ea">

Analysis.
I checked Cloudtrail logs and StepFunctions : I see that user request for Elevated access  written in DynamoDB, also I can see one of the steps in Stepfunction in pending/waiting state as Approver needs to approve it. 
But since Approver not able to see request, he is not able to Approve it.
So need help in debugging this issue.

**Comment by flexelem** [comment]
We are having the same issue started to happen since yesterday. `requests` dynamodb table has request items with empty email field which is probably the source of the problem about not seeing current requests.

**Comment by tawoyinfa** [comment]
@flexelem and @banagevikas  what version are you on ?

**Comment by flexelem** [comment]
@tawoyinfa we are using 1.1 The issue went away when I removed all data from dynamo tables. But couldn't figure it out why emails were not getting persisted.

**Comment by banagevikas** [comment]
@tawoyinfa For us issue is still there. Regarding the version, any specific version you are looking for? If I check the version under path `amplify > config > project-config.json`, TEAMIDCAPP version is 3.1.

**Comment by carlaabanes** [comment]
facing this issue too... approver cannot see the requests.... I installed TEAM 1.1
what is the workaround for this @tawoyinfa ?

thank you.

**Comment by banagevikas** [comment]
> @flexelem is the issue resolved now ?

nope :(

**Comment by carlaabanes** [comment]
For my case, this is not an issue anymore. I understand that a requestor cannot be the same person as the approver. Hence requestor cannot view his own requests for approval. This is by design. 
I have done further testing including different users making requests and as the approver, I can see their requests for approval when I log in.

**Comment by banagevikas** [comment]
In my case, requestor and approver are different. Any workaround guys ?
