### ISSUE TITLE
Eligibility Page not loading 

### ISSUE THREAD

**Issue by carlaabanes** [aws-samples/iam-identity-center-team#231]
**Describe the bug**
When navigating to the Administration menu > Eligibility policy, the page does not load.

**To Reproduce**
1. Go to Administration on left side panel
2. Click on Eligibility policy
3. The page does not load and seems to redirect to another link
4. See error on the web developer tool on firefox or dev tool on chrome

**Expected behavior**
The eligibility policy should load as expected 
https://aws-samples.github.io/iam-identity-center-team/docs/guides/admin.html 

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma
 - Browser - tried on chrome, safari and firefox

**Additional context**
From the web developer tool below error on console tab can be seen
TypeError: _e is null
    Rq Eligible.js:862
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    Rq Eligible.js:495

**Comment by tawoyinfa** [comment]
@carlaabanes this might be related to the issue #140.  Try follwoing the guidance on there and let me know if the issue persist.

**Comment by carlaabanes** [comment]
I added the permission set to my team management account, from the IDC the permission set is 'Provisioned'. But I still get the blank page for eligibility policies page.

**Comment by tawoyinfa** [comment]
The permission set should be added to the organisation management account. Try this and let me know how it goes

**Comment by carlaabanes** [comment]
Hi @tawoyinfa , thank you for your replies. I am trying to deploy the TEAM solution in a delegated account and having a new error 

Resource handler returned message: "Invalid request provided: User: arn:aws:sts::549875961734:assumed-role/TEAM-IDC-APP-AmplifyRole-4caiBBU2IH9Q/BuildSession is not authorized to access this resource (Service: CloudTrail, Status Code: 400, Request ID: b0d2741d-afa2-47aa-af41-f5a656323b5b)" (RequestToken: b5fa1a30-04d5-44e8-408d-0587f37cb512, HandlerErrorCode: InvalidRequest)

I verified that the role has administrator access and there is no deny policy in cloudtrail for this account.

Appreciate if you can help to take a look. thank you.

**Comment by carlaabanes** [comment]
Hi @tawoyinfa 

I managed to deploy in the delegated account for IDC and the page is loading and behaving as expected now. Thank you!

**Comment by carlaabanes** [comment]
Hi @tawoyinfa

I managed to deploy in the delegated account for IDC and the page is loading and behaving as expected now. Thank you
