### ISSUE TITLE
OU's not loading in  Eligbility policy

### ISSUE THREAD

**Issue by dilipsun** [aws-samples/iam-identity-center-team#235]
**Bug**
Eligibility policy fails to load OU's and returns blank page while trying to update .

**Expected behavior**
Eligibility policy should load the Ou's for us to select and update the policy.

**Additional context**
We had a similar issue while getting  accounts from OU's which was fixed after few changes .

Ref: https://github.com/aws-samples/iam-identity-center-team/issues/162
![image](https://github.com/aws-samples/iam-identity-center-team/assets/20889304/29b94ec7-d694-4d8c-8bfc-241f68f40daa)

**Comment by carlaabanes** [comment]
I had the similar problem. To fix this, you have to make sure that the AWS account you are deploying to is the delegated admin account for your organization IDC. You can verify which account is your delegated admin account by going to your AWS console, IDC, go to settings, and on the management tab, view the delegated administrator. Thats the account you should deploy the TEAM to.
