### ISSUE TITLE
Deprecated Lambda runtimes

### ISSUE THREAD

**Issue by lukasgabi** [aws-samples/iam-identity-center-team#242]
**Describe the bug**
The solution currently deploys some login related Lambdas that use Node.js 16.x as runtime, which will be deprecated by June 12, 2024.

**Comment by maunzCache** [comment]
My customer has the same issue but i fail to find any code related to that issue. The nodejs lambda runtimes are set to 18.x.

The only time node 16 is mention is in the package.json see `npm explain @tsconfig/node16`. Not sure if there is some amplify magic creating these runtimes.

**Comment by rjbaker** [comment]
The functions are deployed by the [amplify-cli](https://github.com/aws-amplify/amplify-cli/pull/11317) tool as part of the deployment process. They're not part of the TEAM project. The latest TEAM release uses an old version, but there is a commit on the main branch with a fix - which you can cherry pick into a fork, or deploy from the main branch. We're still waiting for a stable release of TEAM.

https://github.com/aws-samples/iam-identity-center-team/pull/166

**Comment by maunzCache** [comment]
Ah you are right. Didn't compare with the 1.1.1 tag. So this is basically fixed but not released with a new version.
