### ISSUE TITLE
Permissions not loading in Add Eligibility Policy form

### ISSUE THREAD

**Issue by vforvarun** [aws-samples/iam-identity-center-team#245]
**Describe the bug**
All drop downs in the "Add Eligibility Policy form" are properly loading except the "Permission" drop down.

**To Reproduce**
1. Go to 'Administration -> Eligibility policy'
2. Click on 'Add policy' button.
3. Select "Entity Type", Enter the "Ticket No", Select the "List of Eligible OUs".
4. When we try to select permissions, no permission sets are displayed.

**Expected behavior**
Permission sets should be automatically load and be able to select.

**Comment by vforvarun** [comment]
I found that if TEAM is deployed in its own account, then if the existing permission sets from the MGMT account will be ignored, that's when we don't any permission sets loaded. However, when you create new permission sets in the TEAM account, the permission sets are displayed.

**Comment by saas-zach-dunton** [comment]
To add some more information, the Permission Sets don't seem to need to be created by the TEAM account, but they do need to be created after TEAM is set up. I was trying to solve this problem and created a new Permission Set in the management account that was also picked up by TEAM.

TEAM does not seem to pick upon Permissions Sets created before TEAM was set up
