### ISSUE TITLE
Error loading permission sets while creating Eligibility policy

### ISSUE THREAD

**Issue by vgsachin839** [aws-samples/iam-identity-center-team#274]
**Describe the bug**
@tawoyinfa: With reference to the closed issue #261 which is still not resolved. 

When we are trying to create an eligibility policy, UI is crashing, and we are getting "error fetching permissions" message as shown in the attached screenshot, in Developer Tools console in browser. We tested with both Chrome and Edge.

**Expected behavior**
Permission Sets should be loaded successfully in the Permissions dropdown while creating the Eligibility Policy.

**Screenshots**
![Eligibility_Policy_Error_28Jun2024](https://github.com/aws-samples/iam-identity-center-team/assets/100936221/563dfdb9-ac67-4d70-8918-bfcbc6c56d7d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 
- OS: Windows 11
 - Browser: Edge
 - Version: Edge Version 125.0.2535.85 (Official build) (64-bit)

**Additional context**
@tawoyinfa  This fix might be similar to the getOUs issue that was fixed in the latest release 1.1.2

**Comment by tawoyinfa** [comment]
@vgsachin839  This issue has been fixed in the latest commit. Let me know if you are still facing the problem
