### ISSUE TITLE
OUs not loading in Approver Policy

### ISSUE THREAD

**Issue by iankyslytsya** [aws-samples/iam-identity-center-team#275]
**Describe the bug**

![image](https://github.com/aws-samples/iam-identity-center-team/assets/105648500/d5776795-5d83-4c34-a3be-f2a94e5b11ad)

OUs never load when creating a new Approver Policy.

v1.1.2

**Additional context**
OUs load successfully when creating an Eligibility policy.

**Comment by tawoyinfa** [comment]
@iankyslytsya  thanks for reporting this
