### ISSUE TITLE
Unable to Configure eligibility policy

### ISSUE THREAD

**Issue by svnaresh** [aws-samples/iam-identity-center-team#283]
### Discussed in https://github.com/aws-samples/iam-identity-center-team/discussions/282

<div type='discussions-op-text'>

<sup>Originally posted by **svnaresh** July 18, 2024</sup>
I am unable to configure eligibility policy because when i login to TEAM i am not getting  Administration section. We have Active Directory integrated with IDC and i created team admin group in the AD and added my user in this group. In the SSO TEAM Application I gave access to that AD group. So I am able to login to the TEAM UI but not seeing the  Administration section.
Please let me know if any configuration need to modify to see  Administration section.

Thanks in advance.
Venkat Naresh

</div>

**Comment by jperdomo-clouxter** [comment]
Same here
