### ISSUE TITLE
Evaluate Feasibility of creating Eligibility Policy outside of the TEAM solution

### ISSUE THREAD

**Issue by shaktisingh822** [aws-samples/iam-identity-center-team#287]
**Describe the bug**

@tawoyinfa We are looking for a way to avoid doing TEAM activity via TEAM Console. Such as creating eligibility and approver policy. It would be really great if you can provide some input on this. 

We are exploring the feasibility of developing an eligibility or approver policy outside of the team console, perhaps through APIs or another programmatic method? Currently, we manage everything manually through the team console—creating eligibility policies, approver policies, approving the request, revoking approvals, and so on. To minimize management overhead, we need programmatic or Api's way of executing the above activities. 

**Expected behavior**
We can execute most of the TEAM activity using API's or programmatically, to avoid management overhead.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 127.0.2651.74 (Official build) (64-bit)

**Additional context**
We are looking for a way to avoid doing TEAM activity via TEAM Console. It would be really good if we can do this TEAM activities such as creating eligibility and approver policy using api's, or programmatically.

**Comment by mbuotidem** [comment]
Perhaps https://aws-samples.github.io/iam-identity-center-team/docs/deployment/configuration/cognito_machine_auth.html#retrieve-machine-authentication-credentials and https://aws-samples.github.io/iam-identity-center-team/docs/deployment/configuration/cognito_machine_auth.html#using-the-terraform-provider would be helpful.
