### ISSUE TITLE
run deployment script doesn't deploy repo

### ISSUE THREAD

**Issue by mhintz-clickup** [aws-samples/iam-identity-center-team#31]
**Describe the bug**
https://aws-samples.github.io/iam-identity-center-team/docs/deployment/deployment_process.html#run-deployment-script
This step states it will create a repo. That is not correct. If you look at the template.yml file, you can see it doesn't do this.
What I had to do was manually create the repo, clone it locally, change the origin, then push it to codecommit in AWS Cloudshell.

**To Reproduce**
1. Go to here: https://aws-samples.github.io/iam-identity-center-team/docs/deployment/deployment_process.html#run-deployment-script
2. Try to ./deploy.sh
3. Cloudformation will FAIL if you haven't already created the repository in codecommit. 

**Expected behavior**
Repo is cloned down and created for me.

**Screenshots**
I nuked the stack so dont' have but it was general error message stating it can't pull from that repo since it didn't exist (which was correct).

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome

**Additional context**
This whole thing feels very janky with having to run shell scripts. Never seen this before in AWS but I'm guessing this is first step and then there will be an EASY button within the IAM Identity Center console (or CLI but that still isn't great for Identity Center). Hopefully this will get easier and be built-in.

**Comment by mhintz-clickup** [comment]
I did also ask support and they ran into same issue. It was also their first time even seeing this.

**Comment by tawoyinfa** [comment]
@mhintz-clickup the repo creation is not done in the template.yml  but by the [deploy.sh](https://github.com/aws-samples/iam-identity-center-team/blob/c64694cd2b8fd8f7cc6d5f431d54366f350779f7/deployment/deploy.sh#L24) script (see line 24). 

Can you share the exact error you get when you deploy the script. 

Also, this is not an AWS managed service that is natively available but an open source solution that augments identity center.

**Comment by mhintz-clickup** [comment]
well crap. IDK what happened (maybe it was me but don't recall doing it) but those lines are commented out. Sorry about that and thanks. 

I have a separate issue that I may open up for Admin as I got it working in my dev but prod isn't working. I'll do another issue though if I can't figure it out.
