### ISSUE TITLE
[Feature Request] - Enable custom domain

### ISSUE THREAD

**Issue by mazzolia-prom** [aws-samples/iam-identity-center-team#32]
**Describe the bug**
Hi, 
we are trying to set up an amplify custom domain, to serve as frontend but we can't figure out.

**To Reproduce**
We created the amplify domain and associated to the amplify app

<img width="1221" alt="Screenshot 2023-07-06 at 09 13 22" src="https://github.com/aws-samples/iam-identity-center-team/assets/75729390/17ec0b60-47b0-423c-8a69-c2cc304a70d1">

we set up the Identity center APP

Application start URL = https://d140lbzcafqm2w-prod.auth.eu-west-1.amazoncognito.com/authorize?client_id=1prrp5ip6hno5l3qb96vomrauc&identity_provider=IDC&response_type=code&scope=aws.cognito.signin.user.admin+email+openid+phone+profile&redirect_uri=https://team-request.prometeiasaas.com/&idp_identifier=IDC

but on click

<img width="790" alt="Screenshot 2023-07-06 at 09 16 11" src="https://github.com/aws-samples/iam-identity-center-team/assets/75729390/aab9892a-b077-4de0-9d2d-a1accb1bac21">

the redirect uri specified in the Application start URL goes to the Amplify default domain instead the custom domain

<img width="1223" alt="Screenshot 2023-07-06 at 09 16 38" src="https://github.com/aws-samples/iam-identity-center-team/assets/75729390/4fe95913-56ee-4ea7-b74a-d6b4052e465a">

this is the cognito application web client

<img width="737" alt="Screenshot 2023-07-06 at 09 19 53" src="https://github.com/aws-samples/iam-identity-center-team/assets/75729390/31781f0b-09a0-4a3b-a264-cab1cc4f55f1">

**Expected behavior**
cognito redirect to the custom domain

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Chrome
  - Version 114.0.5735.198

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tawoyinfa** [comment]
@mazzolia-prom can you try removing the default amplify domain from the allowed callback URLs and retaining only your custom domain ?

**Comment by EGHPrometeia** [comment]
@tawoyinfa  I have the same problem. I tried to remove the default amplify domain from the allowed callback URLs, retaining only my custom domain. If I try to access the app from SSO, I am redirected to the custom domain. However,  I receive a configuration_mismatch (400) error when I click on the 'Federated Sign In' button.

**Comment by karl-mentzer-vf** [comment]
Vote for Feature

**Comment by ffgarciam** [comment]
We would like this feature as well.
