### ISSUE TITLE
Requesting Access to Management Account Using TEAM: Possible Workarounds and Solutions

### ISSUE THREAD

**Issue by maxflynn1998** [aws-samples/iam-identity-center-team#326]
In the TEAM documentation, it states the following:

The delegated administrator account (and TEAM) by design cannot be used to perform the following tasks:

     - Enable or disable user access in the management account
     - Manage permission sets provisioned in the management account

Given this limitation, is there any way to enable users to request access to the management account?

I was considering the following potential solutions:
     - Modifying the TEAM code to include logic for handling breakglass requests specifically for the management account.
     - Leveraging Cross-Account Access by creating a cross-account IAM role in the management account that can be assumed when needed.
     - Deploying the TEAM application directly inside the management account to handle requests for that account specifically.

Would any of these approaches work, or are there alternative solutions to achieve this functionality?

**Comment by tawoyinfa** [comment]
There is instruction here on [how to deploy in the management account](https://aws-samples.github.io/iam-identity-center-team/docs/deployment/deployment_process.html#deploying-team-into-management-account)
