### ISSUE TITLE
[Soft Bug] Quota limit on CloudTrail Event Data Stores is 10 per account

### ISSUE THREAD

**Issue by billyjbryant** [aws-samples/iam-identity-center-team#34]
**Describe the bug**
There is a hard cap of 10 Event Data Stores per region in an account. If you are using multi-region (or all regions) then this is further limited by the regions you specify. In the case of an Organization, since the TEAM app deploys an Organization CloudTrail Lake Data Store, this limit effects the entire org.

If deploying the backend fails after the cfn template at `amplify/backend/custom/cloudtrailLake/cloudtrailLake-cloudformation-template.json` is deployed, the stack will rollback initiating a deletion event for the CloudTrail Security Lake Event Data Store that was created. The deletion takes 7 days and while the Data Store is pending deletion, it occupies a space in the service quota which cannot be consumed. 

In my case, a modification to the Step Functions, which do not rely on the CloudTrail Event Data Store, failed causing the stack to roll-back. Repeated attempts at the deployment before determining the cause of the failure, caused the service limit for the account to be exhausted.

As this bug was found through modification of the application, I am not sure it is a bug per say, as much as it is an annoyance and something that should be avoided at all costs if possible by changing the order of deployment so that the CloudTrail lake is deployed immediately prior to the functionalities that require it and ensuring that failures of components which do not have a dependency upon it, do not incur un-necessary burden. 

I am now in the state that I cannot attempt to re-deploy the stack until this time next week, once all of the data stores have been deleted. 

**To Reproduce**
Make a modification to any portion of the application such that the Amplify stack is created but the backend deployment fails after the CFN Stacksets have begun deployment. 

**Expected behavior**
The CloudTrail Lake CFN Stack should be deployed as late in the backend deployment lifecycle as possible as to reduce the possibility of such a negative state. 

**Screenshots**
Error: 
![backend deployment error](https://github.com/aws-samples/iam-identity-center-team/assets/3013565/8db90c42-a00a-4371-ad3a-b3dc560e49bc)

DataStores:
![cloudtrail lake event data stores](https://github.com/aws-samples/iam-identity-center-team/assets/3013565/e8d5c59e-b61a-40b3-b961-563751571440)

Quota:
![cloudtrail event data stores quota](https://github.com/aws-samples/iam-identity-center-team/assets/3013565/e661fc70-6190-468f-a7b4-5d037406dad2)

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by tawoyinfa** [comment]
@billyjbryant I dont have visibility into how much customizations you have done to your implementation of the solution.
You can change the order of deployment by adding a dependency in the amplify [backend-config.json](https://github.com/aws-samples/iam-identity-center-team/blob/01672cb985daf6995fb4c1ceac3507a1a2098870/amplify/backend/backend-config.json#L86) file
