### ISSUE TITLE
[Feature Request] - Include all details from request in notification

### ISSUE THREAD

**Issue by mhintz-clickup** [aws-samples/iam-identity-center-team#35]
I saw another reqeust to use SNS instead of SES which would be fantastic. To complete the cycle of ticket creation though, inculding all of the details of the request would be helpful. As of today, I'd be copy/pasting each request into a ticket since the Email doesn't contain all the details.

This product is pretty great and appreciate the continued development!

**Comment by tawoyinfa** [comment]
@mhintz-clickup thanks for the comment. The [Feedback form](https://pulse.aws/survey/PZDTVK85) is our mechanism for getting feedback and evaluating feature requests. Subsquently we will provide updates on the repo's discussions page.
