### ISSUE TITLE
 intermittent failures around access requests that did not show up in the approvals list

### ISSUE THREAD

**Issue by mattcenis** [aws-samples/iam-identity-center-team#47]
**Describe the bug**
If I submit a TEAM request, there are intermittent failures around access requests that did not show up in the approvals list nor did they send out the usual notification emails.  

**To Reproduce**
1. Go to 'Team IDC application and submit a team request'
2. Click on 'Create TEAM Request'
3. Submit the request
4. As an approver click on "Approve Requests"
5. There will be no approvals available to approve.

**Expected behavior**
The request should show in the approve requests window

**Additional context**
If the request is cancelled, and resubmitted, generally the second request does show up.

**Comment by jeffsec-aws** [comment]
Can you provide more details about the approvals that don't show up as the process that you describe is the happy path with the bad result.

Can you provide information about the requestor? the request? The role requested? the approver profile?

I am not looking fr the exact values but expressions of lowercase/uppercase/mixedcase representation.

**Comment by jeffsec-aws** [comment]
might be linked to:
- https://github.com/aws-samples/iam-identity-center-team/issues/30
- https://github.com/aws-samples/iam-identity-center-team/issues/18

**Comment by jeffsec-aws** [comment]
Updating to version 1.0.5 solved the issue.

**Comment by mattcenis** [comment]
Updating to 1.0.5 didn't solve the issue

**Comment by tawoyinfa** [comment]
@mattcenis can you try upgrading to the latest commit 55a17a1. Let me know if this resolves the issue for you.

**Comment by taylorwilliams** [comment]
@mattcenis did the upgrade fix things for you? We're seeing similar issues. We cannot upgrade right this moment due to [upgrade issue]([https://github.com/aws-samples/iam-identity-center-team/issues/77](http://github.com/aws-samples/iam-identity-center-team/issues/77)). But keen to know how it worked for you in meantime.

**Comment by jeffsec-aws** [comment]
yes we got confirmation the issue was resolved with the last version @taylorwilliams

**Comment by jeffsec-aws** [comment]
@mattcenis can you update here and close it please?
