### ISSUE TITLE
Doc Bug - Install "jq" should be a Prerequisites in setup

### ISSUE THREAD

**Issue by karl-mentzer-vf** [aws-samples/iam-identity-center-team#52]
**DOCUMENTATION BUG**

The page at https://aws-samples.github.io/iam-identity-center-team/docs/deployment/prerequisites.html does not outline the requirement for jq however the deploy scripts contain CLI command sequences which use jq

However jq is not installed by Amazon Linux by default so return values fail.

**Suggested fix**

instruct user to install jq by running:

sudo yum install jq

**Comment by tawoyinfa** [comment]
@karl-mentzer-vf This is already outlined in the prerequisites section here - https://aws-samples.github.io/iam-identity-center-team/docs/deployment/prerequisites.html#development-environment-setup
