### ISSUE TITLE
TEAM" does not start, the site keeps loading.

### ISSUE THREAD

**Issue by Artimen7** [aws-samples/iam-identity-center-team#56]
**Describe the bug**
We have an IAM Identity Center account connected to an Active Directory. Users are created in Active Directory, and then AWS directly consumes that data.
When performing attribute mapping from the application created in IAM Identity Center for the "TEAM IDC APP" team, we are stuck on the Federated Sign-In screen without progressing or showing an error.
Upon further investigation, we have noticed that users who are directly assigned in the IAM Identity Center app for the "TEAM IDC APP" team do not have attributes; they only have a user ID. We understand that this is because IAM Identity Center, being connected to AD, retrieves user attributes and data in real-time from the Active Directory.
Is it possible to set up another attribute mapping using Okta, or utilize the user ID provided by IAM Identity Center?
I send some screenshot about what we have and what it´s happend.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/aws-samples/iam-identity-center-team/assets/77062390/6ccb79af-8c5e-4332-8436-8793c75053a5)

![image](https://github.com/aws-samples/iam-identity-center-team/assets/77062390/2ea49008-809f-4081-a300-0d18d36df0a0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tawoyinfa** [comment]
@Artimen7 did you configure the attribute mapping for the TEAM application on Identity Center following the steps [here](- https://aws-samples.github.io/iam-identity-center-team/docs/deployment/configuration/idc.html#configure-attribute-mapping) ?

**Comment by Artimen7** [comment]
Hello,

Yes, we followed the steps and copied the attributes as is.
To give a little more context, we have two Okta locations, let's call them "Okta1" and "Okta2".
In the Okta1 integration, the Identity Center was integrated directly into Okta, so these attributes work perfectly and the TEAM is working.

In Okta2, the Identity Center is integrated into Active Directory, so the attributes are different (this is in the attached ticket) and I understand that the error is coming from there, as the attributes do not match, and it is trying to run TEAM.

PS: as additional information, we are reading the AWS document and linking to the available attributes, but when changing the "subject" of the application, it breaks and does not load TEAM. I don't know if it is possible to alter it in the code to match the AD attributes, but since we don't know what behavior may occur, we don't do it yet.
