### ISSUE TITLE
Email Notifications CC approvers, should we consider BCC?

### ISSUE THREAD

**Issue by andyt10** [aws-samples/iam-identity-center-team#68]
I've noted that email notifications CC approvers.
Should we consider moving to BCC, at the very least for emails TO the requester, (currently) CC-ing the approvers?
[e.g this one](https://github.com/aws-samples/iam-identity-center-team/blob/91a609ab525d4f40e155cb0318f210022cd61d42/amplify/backend/custom/stepfunctions/stepfunctions-cloudformation-template.json#L55)

I don't so much see this as a privacy/security issue regarding email addresses, or even a bug, more a case of preventing requesters/approvers from replying all when one approver (i.e the person actioning) might want to contact the requester...or perhaps also to prevent requesters emailing approvers again.

I believe the general use case when sending out automated emails is NOT to use CC. 

Keen to hear thoughts of others, especially those that might like CC over BCC.

**Additional context**
I see the work in #54 (to add Slack and others) moves notifications to Lambda. Perhaps the changes could be added there after the merge. 
I don't see this as a big issue, more just a nice tidy up. 
If others agree, I will make the change after #54 is merged. 😄

**Comment by anthonyskentzosuts** [comment]
+1 for bcc
