### ISSUE TITLE
TEAM Groups privileges conflict when a user is assigned to multiple groups

### ISSUE THREAD

**Issue by asaf400** [aws-samples/iam-identity-center-team#76]
**Describe the bug**
In our SSO provider which is connected to AWS Identity Center on our Organization account,
We have these _groups_, for which have assigned the groups to these **TEAM roles** :
- **Administrator** <-- _AWS-Admins_
- **Auditor**           <-- _AWS-PowerUsers_
- **Requestor**       <-- _AWS-Developers_

When an administrator is part of both PowerUsers and Admins groups,
TEAM doesn't grant the admin user the privileges of entering the configuration here:

<img width="385" alt="2023-09-10 11_21_42-TEAM _ Temporary Elevated Access Management" src="https://github.com/aws-samples/iam-identity-center-team/assets/14169006/2ae21321-1360-45b2-a613-1033caf51292">

The whole `Administration` section is missing in the left pane.
This suggest that the TEAM app, uses the principle of least privilege (PoLP),
but also upon merging/calculating the user privileges, the role with the least privileges takes precedence over any other.

I would guess this is the current state:
Requestor > Approver >= Auditor > Administrator

So when an admin has any other group, he is 'demoted' to that group's level.

**To Reproduce**
Add an admin user to a Lower-permissions group
Login again to refresh user groups

**Expected behavior**
Admin retains his higher privileges even though he is part of any other groups
or, have add a deployment parameter to flip the behavior, so both ways could be achieved

Requestor > Approver >= Auditor > Administrator
or
Administrator > Auditor >= Approver > Requestor 

This issue is somewhat similar to this #61

**Comment by tawoyinfa** [comment]
@asaf400  This shouldnt be the case. The admin should see the adminstration section even if they belong to other groups. If this is the first time the admin is signing into the application they would have to logout and sign in again before they can see the administration section. Have you tried doing this ?

**Comment by lvthillo** [comment]
I have the same user in an admin group and in an auditor group and I can see all tabs.

**Comment by asaf400** [comment]
@lvthillo I will retest this, maybe I was part of the approver group and not auditors

@tawoyinfa I did try to logout and logback in again, I even manually removed myself from the lower tier group in Cognito,
but upon login, I was ofc re-added to it, and I still wasn't seeing the admin section..

Only when I removed myself from our IDP PowerUsers, which meant I was only part of TEAM admins groups, I was able to see..
I'll retest this as well, and post more screenshots, as the one I took and uploaded here, is after I made the change and was able to see the admin section..
