### ISSUE TITLE
TEAM with Control Tower

### ISSUE THREAD

**Issue by muradalm** [aws-samples/iam-identity-center-team#80]
Hi,

I have Control Tower for my AWS Organization, and i have delegated Account to manage the IAM and Identity Center (SSO).
I have checked the prerequisites of the solution, and it was mentioned the TEAM account will also be configured as delegated admin for: 
- IAM Identity Center
- CloudTrail Lake
- Account management

Since I'm using control tower on the management account (which is Managing Cloudtrail and Account Management) , is it possible to deploy the solution without delegating the Administration of Cloudtrail and Account Management to the TEAM account?

If No, is there any workaround to delegate the CloudTrail Lake and Account management to TEAM account without breaking Control Tower Landing Zone ?

Thanks !

**Comment by lvthillo** [comment]
1) I don't think it's possible to deploy this solution properly without configuring the delegated admins in the TEAM account.
2) I'm not that familiar with Control Tower. You're managing account management with CT. This is done from within the management account. Is there a delegated admin for account management? If not, you can assign it to the TEAM account (which should be your SSO account then). For CloudTrail you can have up to 3 delegated admins I think.

```
$ aws organizations list-delegated-administrators --service-principal cloudtrail.amazonaws.com
$ aws organizations list-delegated-administrators --service-principal account.amazonaws.com
```

I hope I understand your use case correctly.

**Comment by lvthillo** [comment]
@muradalm 

There is a [delegated admin for account management](https://docs.aws.amazon.com/accounts/latest/reference/using-orgs-delegated-admin.html):

`$ aws organizations register-delegated-administrator --service-principal account.amazonaws.com --account-id <xx>`

Registering a delegated admin doesn't mean that your management account will lose the permissions to manage it.
I don't know about the Control Tower setup, but registering delegated admins would not impact existing setups or your management account. The only thing it does is allowing certain actions related to the designated service from within that delegated account. 

Example: first we had no delegated admin for `account.amazonaws.com`. This meant we were only able to update alternate contacts of other accounts from within our root/management account. Now we registered an account as delegated admin for `account.amazonaws.com`. Now we can update alternate contacts for other accounts from within the root/management account, but also from within the delegated admin account.

> AWS accounts within an organization – For member accounts that are part of an AWS organization, a user in the management account or delegated admin account can centrally update any member account in the organization from the AWS Organizations console, or programmatically via the AWS CLI & SDKs. To learn how to do this, see [Update AWS account alternate contacts in your organization](https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-update-contact-alternate.html#manage-acct-update-contact-alternate-orgs). 

[Doc](https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-update-contact-alternate.html)

Same for CloudTrail. Just registering an additional delegated admin should not impact existing setups normally. 

Still, I don't know the details in your organization or with your Control Tower setup, I would recommend to create a test environment/organization to verify if everything works as expected.

**Comment by tawoyinfa** [comment]
@muradalm  check this latest commit out #83 and see if it helps with your use case
