### ISSUE TITLE
Setting 'Ticket Number' is not remaining "Not Required"

### ISSUE THREAD

**Issue by allan-lainch** [aws-samples/iam-identity-center-team#85]
**Describe the bug**
Recently installed the application for the first time and started testing using version 1.1.0.

When I'm logged in to the application as an administrator, if I got into the administrator settings and try to make any of the request settings not required like:

Approval workflow
Comments
Ticket number

There is a brief second where the UI says that they are Not Required, but then they are immediately set back to being Required by the application. 

Is there some configuration requirement I am missing or is this an application issue?

**To Reproduce**
1. Login as admin
2. Go to 'Administration' > 'Settings'
3. Click on 'Edit'
4. Set 'Ticket number' to 'Not required'
5. Click on 'Submit'

**Expected behavior**
Ticket number, Comments or Approval Workflow to become unrequired when toggled off in the administrator request settings, though is still set to Required.

**Comment by tawoyinfa** [comment]
@allan-lainch  acknowledged. Working on a fix

**Comment by tawoyinfa** [comment]
@allan-lainch  use the update.sh script to update to the latest commit [ad88244](https://github.com/aws-samples/iam-identity-center-team/commit/ad88244b35d5d426c383b2b0649562f948eb1572) and let me know if this is fixed for you.

**Comment by allan-lainch** [comment]
Can confirm this is working now.
