### ISSUE TITLE
[Feature Request] Slack notifications into channels it has been invited to

### ISSUE THREAD

**Issue by KashifSaadat** [aws-samples/iam-identity-center-team#86]
Firstly, thank you for the notification support in v1.1.0!

Currently the App sends a message to every user that is an Approver. This can get quite spammy for users in a large Organization, or where there are a large amount of potential Approvers in a Group and everyone gets messaged.

It would be great if we could optionally choose:
1. Whether or not to message Approvers directly
2. When a permission escalation request comes through, the TEAM App can post a message in any Slack channel it has been invited to

**Comment by tawoyinfa** [comment]
@KashifSaadat thanks for the feedback. Your request is a good use case for enabling SNS as a notification option. By subscribing to the TEAM SNS topic, you can build your own custom Slack notification webhook and disable the slack app integration to meet your need.
